
name: gitartwork from a contribution graph
on: 
  push:
  pull_request:
  schedule:
    - cron: '* */24 * * *'
  workflow_dispatch:  
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           user_name: Ramasindi
           text: THALU-RT
